-- pokedex.caracteristica definition
-- Drop table
-- DROP TABLE pokedex.caracteristica;

CREATE TABLE pokedex.caracteristica
(
    idcaracteristica int8        NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    dsaltura         varchar(10) NULL,
    dsidade          varchar(10) NULL,
    nmcaracteristica varchar(70) NULL,
    dspeso           varchar(10) NULL,
    CONSTRAINT caracteristica_pkey PRIMARY KEY (idcaracteristica)
);


-- pokedex.categoria definition
-- Drop table
-- DROP TABLE pokedex.categoria;

CREATE TABLE pokedex.categoria
(
    idcategoria int8         NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    stativo     varchar(255) NOT NULL,
    nmcategoria varchar(70)  NULL,
    CONSTRAINT categoria_pkey PRIMARY KEY (idcategoria)
);


-- pokedex.fraqueza definition
-- Drop table
-- DROP TABLE pokedex.fraqueza;

CREATE TABLE pokedex.fraqueza
(
    idfraqueza int8         NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    stativo    varchar(255) NOT NULL,
    nmfraqueza varchar(70)  NULL,
    CONSTRAINT fraqueza_pkey PRIMARY KEY (idfraqueza)
);


-- pokedex.genero definition
-- Drop table
-- DROP TABLE pokedex.genero;

CREATE TABLE pokedex.genero
(
    idgenero int8         NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    stativo  varchar(255) NOT NULL,
    nmgenero varchar(70)  NULL,
    CONSTRAINT genero_pkey PRIMARY KEY (idgenero)
);


-- pokedex.habilidade definition
-- Drop table
-- DROP TABLE pokedex.habilidade;

CREATE TABLE pokedex.habilidade
(
    idhabilidade int8         NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    stativo      varchar(255) NOT NULL,
    nmhabilidade varchar(70)  NULL,
    CONSTRAINT habilidade_pkey PRIMARY KEY (idhabilidade)
);


-- pokedex.categoriahabilidade definition
-- Drop table
-- DROP TABLE pokedex.categoriahabilidade;

CREATE TABLE pokedex.categoriahabilidade
(
    idcategoriahabilidade int8         NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    stativo               varchar(255) NOT NULL,
    nmcategoriahabilidade varchar(70)  NULL,
    idhabilidade          int8         NULL,
    CONSTRAINT categoriahabilidade_pkey PRIMARY KEY (idcategoriahabilidade),
    CONSTRAINT categoriahabilidade_habilidade FOREIGN KEY (idhabilidade) REFERENCES pokedex.habilidade (idhabilidade)
);


-- pokedex.pokemon definition
-- Drop table
-- DROP TABLE pokedex.pokemon;

CREATE TABLE pokedex.pokemon
(
    idpokemon        int8        NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    nmpokemon        varchar(50) NULL,
    idcaracteristica int8        NULL,
    idcategoria      int8        NULL,
    idgenero         int8        NULL,
    CONSTRAINT pokemon_pkey PRIMARY KEY (idpokemon),
    CONSTRAINT pokemon_categoria FOREIGN KEY (idcategoria) REFERENCES pokedex.categoria (idcategoria),
    CONSTRAINT pokemon_genero FOREIGN KEY (idgenero) REFERENCES pokedex.genero (idgenero),
    CONSTRAINT pokemon_caraceristica FOREIGN KEY (idcaracteristica) REFERENCES pokedex.caracteristica (idcaracteristica)
);


-- pokedex.tipofraqueza definition
-- Drop table
-- DROP TABLE pokedex.tipofraqueza;

CREATE TABLE pokedex.tipofraqueza
(
    idtipofraqueza int8         NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    stativo        varchar(255) NOT NULL,
    nmtipofraqueza varchar(70)  NULL,
    idfraqueza     int8         NULL,
    CONSTRAINT tipofraqueza_pkey PRIMARY KEY (idtipofraqueza),
    CONSTRAINT tipofraqueza_fraqueza FOREIGN KEY (idfraqueza) REFERENCES pokedex.fraqueza (idfraqueza)
);


-- pokedex.tipohabilidade definition
-- Drop table
-- DROP TABLE pokedex.tipohabilidade;

CREATE TABLE pokedex.tipohabilidade
(
    idtipohabilidade int8         NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    stativo          varchar(255) NOT NULL,
    nmtipohabilidade varchar(70)  NULL,
    idhabilidade     int8         NULL,
    CONSTRAINT tipohabilidade_pkey PRIMARY KEY (idtipohabilidade),
    CONSTRAINT tipohabilidade_habilidade FOREIGN KEY (idhabilidade) REFERENCES pokedex.habilidade (idhabilidade)
);


-- pokedex.fraquezapokemon definition
-- Drop table
-- DROP TABLE pokedex.fraquezapokemon;

CREATE TABLE pokedex.fraquezapokemon
(
    idfraquezapokemon int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    idfraqueza        int8 NULL,
    idpokemon         int8 NULL,
    CONSTRAINT fraquezapokemon_pkey PRIMARY KEY (idfraquezapokemon),
    CONSTRAINT fraquezapokemon_fraqueza FOREIGN KEY (idfraqueza) REFERENCES pokedex.fraqueza (idfraqueza),
    CONSTRAINT fraquezapokemon_pokemon FOREIGN KEY (idpokemon) REFERENCES pokedex.pokemon (idpokemon)
);


-- pokedex.habilidadepokemon definition
-- Drop table
-- DROP TABLE pokedex.habilidadepokemon;

CREATE TABLE pokedex.habilidadepokemon
(
    idhabilidadepokemon int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    idhabilidade        int8 NULL,
    idpokemon           int8 NULL,
    CONSTRAINT habilidadepokemon_pkey PRIMARY KEY (idhabilidadepokemon),
    CONSTRAINT habilidadepokemon_pokemon FOREIGN KEY (idpokemon) REFERENCES pokedex.pokemon (idpokemon),
    CONSTRAINT habilidadepokemon_habilidade FOREIGN KEY (idhabilidade) REFERENCES pokedex.habilidade (idhabilidade)
);
