INSERT INTO public.tipo(idTipo, nmTipo) VALUES (1, 'Inseto');
INSERT INTO public.tipo(idTipo, nmTipo) VALUES (2, 'Dragão');
INSERT INTO public.tipo(idTipo, nmTipo) VALUES (3, 'Fada');
INSERT INTO public.tipo(idTipo, nmTipo) VALUES (4, 'Fogo');
INSERT INTO public.tipo(idTipo, nmTipo) VALUES (5, 'Fantasma');
INSERT INTO public.tipo(idTipo, nmTipo) VALUES (6, 'Terra');
INSERT INTO public.tipo(idTipo, nmTipo) VALUES (7, 'Normal');
INSERT INTO public.tipo(idTipo, nmTipo) VALUES (8, 'Psíquico');
INSERT INTO public.tipo(idTipo, nmTipo) VALUES (9, 'Aço');
INSERT INTO public.tipo(idTipo, nmTipo) VALUES (10, 'Escuridão');
INSERT INTO public.tipo(idTipo, nmTipo) VALUES (11, 'Elétrico');
INSERT INTO public.tipo(idTipo, nmTipo) VALUES (12, 'Luta');
INSERT INTO public.tipo(idTipo, nmTipo) VALUES (13, 'Voador');
INSERT INTO public.tipo(idTipo, nmTipo) VALUES (14, 'Planta');
INSERT INTO public.tipo(idTipo, nmTipo) VALUES (15, 'Venenoso');
INSERT INTO public.tipo(idTipo, nmTipo) VALUES (17, 'Pedra');
INSERT INTO public.tipo(idTipo, nmTipo) VALUES (18, 'Água');

INSERT INTO public.fraqueza(idFraqueza, nmFraqueza) VALUES (1, 'Inseto');
INSERT INTO public.fraqueza(idFraqueza, nmFraqueza) VALUES (2, 'Dragão');
INSERT INTO public.fraqueza(idFraqueza, nmFraqueza) VALUES (3, 'Fada');
INSERT INTO public.fraqueza(idFraqueza, nmFraqueza) VALUES (4, 'Fogo');
INSERT INTO public.fraqueza(idFraqueza, nmFraqueza) VALUES (5, 'Fantasma');
INSERT INTO public.fraqueza(idFraqueza, nmFraqueza) VALUES (6, 'Terra');
INSERT INTO public.fraqueza(idFraqueza, nmFraqueza) VALUES (7, 'Normal');
INSERT INTO public.fraqueza(idFraqueza, nmFraqueza) VALUES (8, 'Psíquico');
INSERT INTO public.fraqueza(idFraqueza, nmFraqueza) VALUES (9, 'Aço');
INSERT INTO public.fraqueza(idFraqueza, nmFraqueza) VALUES (10, 'Escuridão');
INSERT INTO public.fraqueza(idFraqueza, nmFraqueza) VALUES (11, 'Elétrico');
INSERT INTO public.fraqueza(idFraqueza, nmFraqueza) VALUES (12, 'Luta');
INSERT INTO public.fraqueza(idFraqueza, nmFraqueza) VALUES (13, 'Voador');
INSERT INTO public.fraqueza(idFraqueza, nmFraqueza) VALUES (14, 'Planta');
INSERT INTO public.fraqueza(idFraqueza, nmFraqueza) VALUES (15, 'Venenoso');
INSERT INTO public.fraqueza(idFraqueza, nmFraqueza) VALUES (17, 'Pedra');
INSERT INTO public.fraqueza(idFraqueza, nmFraqueza) VALUES (18, 'Água');

INSERT INTO public.habilidade(idHabilidade, nmHabilidade) VALUES (1, 'Adaptability');
INSERT INTO public.habilidade(idHabilidade, nmHabilidade) VALUES (2, 'Aftermath');
INSERT INTO public.habilidade(idHabilidade, nmHabilidade) VALUES (3, 'Air Lock');
INSERT INTO public.habilidade(idHabilidade, nmHabilidade) VALUES (4, 'Anger Point');
INSERT INTO public.habilidade(idHabilidade, nmHabilidade) VALUES (5, 'Anticipation');
INSERT INTO public.habilidade(idHabilidade, nmHabilidade) VALUES (6, 'Arena Trap');
INSERT INTO public.habilidade(idHabilidade, nmHabilidade) VALUES (7, 'Bad Dreams');
INSERT INTO public.habilidade(idHabilidade, nmHabilidade) VALUES (8, 'Battle Armor');
INSERT INTO public.habilidade(idHabilidade, nmHabilidade) VALUES (9, 'Blaze');
INSERT INTO public.habilidade(idHabilidade, nmHabilidade) VALUES (10, 'Chlorophyll');
INSERT INTO public.habilidade(idHabilidade, nmHabilidade) VALUES (11, 'Clear Body');
INSERT INTO public.habilidade(idHabilidade, nmHabilidade) VALUES (12, 'Cloud Nine');
INSERT INTO public.habilidade(idHabilidade, nmHabilidade) VALUES (13, 'Color Change');
INSERT INTO public.habilidade(idHabilidade, nmHabilidade) VALUES (14, 'Compound Eyes');
INSERT INTO public.habilidade(idHabilidade, nmHabilidade) VALUES (15, 'Cute Charm');
INSERT INTO public.habilidade(idHabilidade, nmHabilidade) VALUES (16, 'Damp');
INSERT INTO public.habilidade(idHabilidade, nmHabilidade) VALUES (17, 'Download');
INSERT INTO public.habilidade(idHabilidade, nmHabilidade) VALUES (18, 'Drizzle');
INSERT INTO public.habilidade(idHabilidade, nmHabilidade) VALUES (19, 'Drought');
INSERT INTO public.habilidade(idHabilidade, nmHabilidade) VALUES (20, 'Dry Skin');
INSERT INTO public.habilidade(idHabilidade, nmHabilidade) VALUES (21, 'Early Bird');
INSERT INTO public.habilidade(idHabilidade, nmHabilidade) VALUES (22, 'Effect Spore');
INSERT INTO public.habilidade(idHabilidade, nmHabilidade) VALUES (23, 'Filter');
INSERT INTO public.habilidade(idHabilidade, nmHabilidade) VALUES (24, 'Flame Body');
INSERT INTO public.habilidade(idHabilidade, nmHabilidade) VALUES (25, 'Flash Fire');
INSERT INTO public.habilidade(idHabilidade, nmHabilidade) VALUES (26, 'Flower Gift');
INSERT INTO public.habilidade(idHabilidade, nmHabilidade) VALUES (27, 'Forecast');
INSERT INTO public.habilidade(idHabilidade, nmHabilidade) VALUES (28, 'Forewarn');
INSERT INTO public.habilidade(idHabilidade, nmHabilidade) VALUES (29, 'Frisk');
INSERT INTO public.habilidade(idHabilidade, nmHabilidade) VALUES (30, 'Gluttony');

-- INSERT INTO public.pokemon(id, altura, categoria, genero, nomepokemon, peso, idTipo) VALUES (1, '0.4 m', 'Mouse', 'M', 'Pikachu', '6 kg');
-- INSERT INTO public.pokemon(id, altura, categoria, genero, nomepokemon, peso) VALUES (2, '0.7 m', 'Semente', 'M', 'Bulbasaur', '6.9 kg');


